[package]
name = "ve3-shared"
version = "1.0.0"
authors = ["devs@erisprotocol.com"]
edition = "2018"
license.workspace = true

exclude = []

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw-asset.workspace = true
cw721.workspace = true
cw721-base.workspace = true
cw20.workspace = true
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
semver.workspace = true
