[package]
name = "ve3-shared"
description = "ve(3,3) msgs in cosmwasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

exclude = []

[dependencies]
cosmwasm-std = {workspace = true, features = ["stargate"]}
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw-asset.workspace = true
cw-ownable.workspace = true
cw721.workspace = true
cw721-base.workspace = true
cw20.workspace = true
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
semver.workspace = true
cw-address-like.workspace = true

# Tokenfactory
osmosis-std-derive.workspace = true
prost.workspace = true
prost-types.workspace = true