// AT = Address Type
pub const AT_CONNECTOR: &str = "CONNECTOR";
pub const AT_DELEGATION_CONTROLLER: &str = "DELEGATION_CONTROLLER";
pub const AT_ASSET_WHITELIST_CONTROLLER: &str = "ASSET_WHITELIST_CONTROLLER";
pub const AT_REWARD_DISTRIBUTION_CONTROLLER: &str = "REWARD_DISTRIBUTION_CONTROLLER";
pub const AT_LP_STAKING: &str = "LP_STAKING";

pub const DEFAULT_LIMIT: u32 = 10;
pub const MAX_LIMIT: u32 = 100;
