[package]
name = "ve3-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]

cosmwasm-std = { workspace = true, features = ["stargate"] }
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw-asset.workspace = true
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
semver.workspace = true
cw2.workspace = true
cw-utils.workspace = true
ve3-shared.workspace = true
cw-ownable.workspace = true

cw20.workspace = true
cw20-base.workspace = true
cw721.workspace = true
cw721-base.workspace = true

cw-multi-test = { version = "1.1.0", default-features = false, features = ["cosmwasm_1_1", "cosmwasm_1_3"]}

ve3-asset-compounding = {path = "../../contracts/asset-compounding"}
ve3-asset-gauge = {path = "../../contracts/asset-gauge"}
ve3-asset-staking = {path = "../../contracts/asset-staking"}
ve3-bribe-manager = {path = "../../contracts/bribe-manager"}
ve3-connector-alliance = {path = "../../contracts/connector-alliance"}
ve3-connector-emission = {path = "../../contracts/connector-emission"}
ve3-global-config = {path = "../../contracts/global-config"}
ve3-voting-escrow = {path = "../../contracts/voting-escrow"}
ve3-zapper = {path = "../../contracts/zapper"}
phoenix-treasury = {path = "../../contracts/phoenix-treasury"}

astroport = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "9c20f5a7947333c0150457db1a5b342868311d03" }
astroport-pair = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "9c20f5a7947333c0150457db1a5b342868311d03" }
astroport-factory = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "9c20f5a7947333c0150457db1a5b342868311d03" }
astroport-native-coin-registry = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "9c20f5a7947333c0150457db1a5b342868311d03" }
# stader = { git = "https://github.com/stader-labs/lunax.git", package="staking", default-features = false, rev = "20143548e2dea807b343fe6ad60375086af35ea9"}

eris-staking-token = { git = "https://github.com/erisprotocol/contracts-terra.git", default-features = false, rev = "dbcaa4db951f2bec6e239ccf94f25c85f3bed80a"}
eris-staking-hub =  { git = "https://github.com/erisprotocol/contracts-terra.git", default-features = false, rev = "dbcaa4db951f2bec6e239ccf94f25c85f3bed80a"}
eris =  { git = "https://github.com/erisprotocol/contracts-terra.git", default-features = false, rev = "dbcaa4db951f2bec6e239ccf94f25c85f3bed80a"}
protobuf = "=3.2.0"


colored = "2.1.0"
anyhow = "1"
